[package]
name = "snolc"
description = "library engine for the snolc userspace network stack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-executor.workspace = true
async-io.workspace = true
crossbeam-queue.workspace = true
futures.workspace = true
libloading.workspace = true
libc.workspace = true
serde.workspace = true
sha2.workspace = true
snolc-abi = { version = "=0.0.4", path = "../snolc-abi" }
snolc-sdk = { version = "=0.0.4", path = "../snolc-sdk" }
smoltcp = { workspace = true, features = ["std", "medium-ip", "proto-ipv4", "proto-ipv6", "socket-tcp", "socket-udp", "fragmentation-buffer-size-65536", "reassembly-buffer-count-4", "reassembly-buffer-size-65536", "proto-ipv4-fragmentation", "proto-ipv6-fragmentation"] }
thiserror.workspace = true
toml.workspace = true
yamux.workspace = true
