[package]
name = "snolc-carrier-tcp"
description = "TCP carrier for snolc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
async-io.workspace = true
futures.workspace = true
libc.workspace = true
serde.workspace = true
socket2.workspace = true
snolc-sdk.workspace = true
toml.workspace = true

[features]
static-link = []
